// The YourScore avatar set — footballer action silhouettes on the brand palette.
//
// Art is generated by scripts/gen-avatars.mjs (one style anchor, every sibling
// conditioned on it) and lives in public/avatars/. Regenerating the set is a
// script run, not a code change — this file only maps ids to files and labels.
//
// Stored in profiles.avatar_url as a ROOT-RELATIVE PATH, not a data URI. Every
// consumer is an `<img src>` or an SVG `<image href>` in the browser, so the path
// resolves; no OG/Satori route reads avatar_url (checked), which is the one place
// a relative path would break. Older data-URI avatars and external Google photos
// keep working untouched — they're just strings in the same column.

export interface FootballAvatar {
  id: string;
  /** Shown under the tile in the picker. */
  label: string;
}

/**
 * Roles and moments, not people — you pick the player you are, the way you'd pick
 * a character in a game. Each is chosen for a distinct SILHOUETTE, because these
 * are read at 24px in leaderboard rows where detail is worthless and shape is not.
 *
 * Accent follows the brand: lime = action/energy, teal = keeper and the composed
 * moments, gold = wins only.
 */
export const FOOTBALL_AVATARS: FootballAvatar[] = [
  { id: "fan-01", label: "Volley" },
  { id: "fan-02", label: "Keeper" },
  { id: "fan-03", label: "Manager" },
  { id: "fan-04", label: "Header" },
  { id: "fan-05", label: "Knee slide" },
  { id: "fan-06", label: "Sprint" },
  { id: "fan-07", label: "Tackle" },
  { id: "fan-08", label: "Free kick" },
  { id: "fan-09", label: "Bicycle" },
  { id: "fan-10", label: "Punch" },
  { id: "fan-11", label: "Captain" },
  { id: "fan-12", label: "Trophy" },
  { id: "fan-13", label: "Playmaker" },
  { id: "fan-14", label: "Nutmeg" },
  { id: "fan-15", label: "Roar" },
  { id: "fan-16", label: "Chip" },
];

/** Public path for a catalog avatar. Empty string for an unknown id. */
export function avatarSrc(id: string): string {
  return FOOTBALL_AVATARS.some((a) => a.id === id) ? `/avatars/${id}.webp` : "";
}

/**
 * Which catalog avatar an avatar_url corresponds to — for highlighting the
 * current pick. Null for external photos, legacy data-URI avatars, or monograms.
 */
export function avatarIdFromUrl(url: string | null | undefined): string | null {
  if (!url) return null;
  const m = /\/avatars\/(fan-\d{2})\.webp$/.exec(url);
  return m && FOOTBALL_AVATARS.some((a) => a.id === m[1]) ? m[1] : null;
}
