/**
 * PL gated-draft question bundle tests. Run: `node --test src/lib/draft/pl-quiz.test.ts`
 * (Node 24 strips the TS types natively.)
 *
 * These guard the ARTIFACT, not the game maths (that's draft-quiz.test.ts). The bundle is
 * generated by scripts/draft/build-pl-quiz.mjs against the live questions bank, so a bad
 * run — a bank schema change, a filter typo, a half-written file — must fail here rather
 * than ship a gate that deals broken or spoiling questions.
 *
 * Deliberately reads the JSON off disk instead of importing src/lib/draft/pl-quiz.ts:
 * that module is `server-only` and imports through the `@/` alias, neither of which
 * resolves under a bare `node --test`.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

type Q = {
  id: string; q: string; options: string[]; answer: number;
  difficulty: string; category: string;
  scope: "neutral" | "club"; club: string | null;
};

const bundle = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "..", "data", "draft", "pl-quiz.json"), "utf8"),
) as { count: number; neutralCount: number; clubAliases: Record<string, string>; questions: Q[] };

const POOL = bundle.questions;
const NEUTRAL = POOL.filter((q) => q.scope === "neutral");

test("bundle is non-empty and its count matches the questions it carries", () => {
  assert.ok(POOL.length > 0, "empty pool — the gate would have nothing to ask");
  assert.equal(bundle.count, POOL.length);
  // A thin bundle means repeats inside a single 11-question draft become likely.
  assert.ok(POOL.length >= 100, `only ${POOL.length} questions — too thin for an 11-pick gate`);
});

test("every question is a well-formed 4-option multiple choice", () => {
  for (const q of POOL) {
    assert.equal(q.options.length, 4, `${q.id} has ${q.options.length} options`);
    for (const o of q.options) {
      assert.equal(typeof o, "string", `${q.id} has a non-string option`);
      assert.ok(o.trim().length > 0, `${q.id} has a blank option`);
    }
    assert.ok(Number.isInteger(q.answer) && q.answer >= 0 && q.answer < 4, `${q.id} answer index out of range`);
    assert.ok(q.q.trim().length > 0, `${q.id} has a blank prompt`);
  }
});

test("no question offers the same option twice (a duplicate makes the answer ambiguous)", () => {
  for (const q of POOL) {
    const distinct = new Set(q.options.map((o) => o.trim().toLowerCase()));
    assert.equal(distinct.size, 4, `${q.id} repeats an option: ${q.options.join(" | ")}`);
  }
});

test("no answer is ambiguous — it must not contain, or read as, another option", () => {
  // The bank holds a few rows whose answer is two answers concatenated ("The Villans The
  // Lions"), which makes a distractor correct too and marks a right answer wrong.
  for (const q of POOL) {
    const answer = q.options[q.answer];
    const others = q.options.filter((_, i) => i !== q.answer);
    for (const o of others) {
      assert.ok(!(o.length > 3 && answer.includes(o)), `${q.id} answer "${answer}" contains option "${o}"`);
    }
    assert.ok(!/^The .+ The .+$/.test(answer), `${q.id} answer "${answer}" reads as two answers`);
  }
});

test("ids and question text are unique — the same fact can't be asked twice in one draft", () => {
  const ids = new Set<string>();
  const texts = new Set<string>();
  for (const q of POOL) {
    assert.ok(!ids.has(q.id), `duplicate id ${q.id}`);
    ids.add(q.id);
    const t = q.q.trim().toLowerCase();
    assert.ok(!texts.has(t), `duplicate question text: ${q.q}`);
    texts.add(t);
  }
});

test("the bank stays Premier League and stays easy — the brief, encoded", () => {
  for (const q of POOL) {
    assert.ok(["easy", "medium"].includes(q.difficulty), `${q.id} is ${q.difficulty} — too hard for a neutral fan`);
  }
  // The unplayable shape the build script rejects: nobody recalls a mid-table finish.
  // The bank phrases it many ways and a narrow check misses most of them — that's a real
  // bug this bundle shipped with once, so the assertion matches on the finish/position
  // pairing rather than one sentence shape.
  const positional = POOL.filter((q) =>
    /(final|finishing|league)\s+(league\s+)?(position|finish)|(position|place)\s+did\s+.*\bfinish|finish(ed)?\s+(in\s+)?(which|what|where)\b|\bwhere\s+did\s+.*\bfinish/i.test(q.q),
  );
  assert.equal(positional.length, 0, `finishing-position recall leaked in: ${positional.map((q) => `${q.id} "${q.q}"`).join(" · ")}`);
});

test("scope is coherent — neutral carries no club, club-scoped always names one", () => {
  for (const q of POOL) {
    assert.ok(q.scope === "neutral" || q.scope === "club", `${q.id} has scope "${q.scope}"`);
    if (q.scope === "neutral") assert.equal(q.club, null, `${q.id} is neutral but claims club ${q.club}`);
    else assert.ok(q.club, `${q.id} is club-scoped with no club`);
  }
  assert.equal(bundle.neutralCount, NEUTRAL.length, "neutralCount disagrees with the questions it ships");
});

test("no coin flips — a question whose four options are all bare numbers", () => {
  // "How many goals did Salah score in 2024-25?" [28/30/29/31] cannot be answered by knowing
  // football; it's a 1-in-4 guess. In Pro that costs a player AND the streak, which is the
  // opposite of the mode's premise. Scorelines ("2-2") and anything carrying a unit survive,
  // since they aren't bare numbers and are recalled as events rather than tallies.
  const numeric = POOL.filter((q) => q.options.every((o) => /^\d[\d,]*$/.test(String(o).trim())));
  assert.equal(
    numeric.length, 0,
    `coin flips in the bundle: ${numeric.slice(0, 3).map((q) => `"${q.q}" [${q.options.join("/")}]`).join(" · ")}`,
  );
});

test("the neutral pool can stand on its own — it is what a guest sees", () => {
  // A guest, and any player who hasn't picked a club, only ever draws from this. An
  // 11-question gate against a thin neutral pool means repeats inside a single draft.
  assert.ok(NEUTRAL.length >= 50, `only ${NEUTRAL.length} neutral questions — too thin for an 11-pick gate`);
});

test("every club's eligible pool is exactly neutral + their own — nothing foreign", () => {
  // Mirrors eligiblePool() in pl-quiz.ts, which that module builds as [...NEUTRAL, ...own].
  // pl-quiz.ts is `server-only` and imports through the @/ alias, so a bare `node --test`
  // can't load it — this asserts the property on the shipped data instead, and the live
  // API test covers the wiring end to end.
  const byClub = new Map<string, Q[]>();
  for (const q of POOL) {
    if (q.scope !== "club" || !q.club) continue;
    const arr = byClub.get(q.club);
    if (arr) arr.push(q); else byClub.set(q.club, [q]);
  }
  for (const [club, own] of Array.from(byClub)) {
    const pool = [...NEUTRAL, ...own];
    const foreign = pool.filter((q) => q.scope === "club" && q.club !== club);
    assert.equal(foreign.length, 0, `a ${club} fan could be asked about ${foreign[0]?.club}`);
    assert.equal(pool.length, NEUTRAL.length + own.length);
  }
  // And the no-club case (guest, or hasn't picked) is the neutral pool alone.
  assert.equal(NEUTRAL.filter((q) => q.scope === "club").length, 0);
});

test("club scoping is real — no club's questions could reach another club's fans", () => {
  // The whole point of the scoping: a player's pool is neutral + their own club, so a
  // question tagged to a club must never also be reachable as neutral. Duplicated text
  // across scopes would defeat that, since the neutral copy goes to everyone.
  const neutralText = new Set(NEUTRAL.map((q) => q.q.trim().toLowerCase()));
  for (const q of POOL) {
    if (q.scope !== "club") continue;
    assert.ok(
      !neutralText.has(q.q.trim().toLowerCase()),
      `"${q.q}" is tagged to ${q.club} but also sits in the neutral pool — every fan would see it`,
    );
  }
  // Clubs the alias map claims to translate must actually exist as targets, or those
  // supporters silently get zero club questions (the exact bug scoping exists to fix).
  const clubs = new Set(POOL.filter((q) => q.scope === "club").map((q) => q.club));
  for (const entity of Object.values(bundle.clubAliases)) {
    assert.ok(clubs.has(entity), `alias maps to "${entity}" but no question is tagged to it`);
  }
});
