/**
 * PL gated-draft question bundle tests. Run: `node --test src/lib/draft/pl-quiz.test.ts`
 * (Node 24 strips the TS types natively.)
 *
 * These guard the ARTIFACT, not the game maths (that's draft-quiz.test.ts). The bundle is
 * generated by scripts/draft/build-pl-quiz.mjs against the live questions bank, so a bad
 * run — a bank schema change, a filter typo, a half-written file — must fail here rather
 * than ship a gate that deals broken or spoiling questions.
 *
 * Deliberately reads the JSON off disk instead of importing src/lib/draft/pl-quiz.ts:
 * that module is `server-only` and imports through the `@/` alias, neither of which
 * resolves under a bare `node --test`.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

type Q = { id: string; q: string; options: string[]; answer: number; difficulty: string; category: string; entity: string };

const bundle = JSON.parse(
  readFileSync(join(import.meta.dirname, "..", "..", "data", "draft", "pl-quiz.json"), "utf8"),
) as { count: number; questions: Q[] };

const POOL = bundle.questions;

test("bundle is non-empty and its count matches the questions it carries", () => {
  assert.ok(POOL.length > 0, "empty pool — the gate would have nothing to ask");
  assert.equal(bundle.count, POOL.length);
  // A thin bundle means repeats inside a single 11-question draft become likely.
  assert.ok(POOL.length >= 100, `only ${POOL.length} questions — too thin for an 11-pick gate`);
});

test("every question is a well-formed 4-option multiple choice", () => {
  for (const q of POOL) {
    assert.equal(q.options.length, 4, `${q.id} has ${q.options.length} options`);
    for (const o of q.options) {
      assert.equal(typeof o, "string", `${q.id} has a non-string option`);
      assert.ok(o.trim().length > 0, `${q.id} has a blank option`);
    }
    assert.ok(Number.isInteger(q.answer) && q.answer >= 0 && q.answer < 4, `${q.id} answer index out of range`);
    assert.ok(q.q.trim().length > 0, `${q.id} has a blank prompt`);
  }
});

test("no question offers the same option twice (a duplicate makes the answer ambiguous)", () => {
  for (const q of POOL) {
    const distinct = new Set(q.options.map((o) => o.trim().toLowerCase()));
    assert.equal(distinct.size, 4, `${q.id} repeats an option: ${q.options.join(" | ")}`);
  }
});

test("no answer is ambiguous — it must not contain, or read as, another option", () => {
  // The bank holds a few rows whose answer is two answers concatenated ("The Villans The
  // Lions"), which makes a distractor correct too and marks a right answer wrong.
  for (const q of POOL) {
    const answer = q.options[q.answer];
    const others = q.options.filter((_, i) => i !== q.answer);
    for (const o of others) {
      assert.ok(!(o.length > 3 && answer.includes(o)), `${q.id} answer "${answer}" contains option "${o}"`);
    }
    assert.ok(!/^The .+ The .+$/.test(answer), `${q.id} answer "${answer}" reads as two answers`);
  }
});

test("ids and question text are unique — the same fact can't be asked twice in one draft", () => {
  const ids = new Set<string>();
  const texts = new Set<string>();
  for (const q of POOL) {
    assert.ok(!ids.has(q.id), `duplicate id ${q.id}`);
    ids.add(q.id);
    const t = q.q.trim().toLowerCase();
    assert.ok(!texts.has(t), `duplicate question text: ${q.q}`);
    texts.add(t);
  }
});

test("the bank stays Premier League and stays easy — the brief, encoded", () => {
  for (const q of POOL) {
    assert.ok(["easy", "medium"].includes(q.difficulty), `${q.id} is ${q.difficulty} — too hard for a neutral fan`);
    assert.ok(q.entity && q.entity.length > 0, `${q.id} has no entity`);
  }
  // The unplayable shape the build script rejects: nobody recalls a mid-table finish.
  // The bank phrases it many ways and a narrow check misses most of them — that's a real
  // bug this bundle shipped with once, so the assertion matches on the finish/position
  // pairing rather than one sentence shape.
  const positional = POOL.filter((q) =>
    /(final|finishing|league)\s+(league\s+)?(position|finish)|(position|place)\s+did\s+.*\bfinish|finish(ed)?\s+(in\s+)?(which|what|where)\b|\bwhere\s+did\s+.*\bfinish/i.test(q.q),
  );
  assert.equal(positional.length, 0, `finishing-position recall leaked in: ${positional.map((q) => `${q.id} "${q.q}"`).join(" · ")}`);
});

test("no single club dominates the gate", () => {
  const byEntity = new Map<string, number>();
  for (const q of POOL) byEntity.set(q.entity, (byEntity.get(q.entity) ?? 0) + 1);
  for (const [entity, n] of Array.from(byEntity)) {
    const share = n / POOL.length;
    assert.ok(share <= 0.2, `${entity} is ${Math.round(share * 100)}% of the bank — the gate reads as a ${entity} quiz`);
  }
});
